import type { Level } from "@/game/bot";
import type { Power } from "@/game/powerups";

export type Lang = "es" | "en";

export const strings = {
  es: {
    title: "La Barra",
    tagline: "Futbolito de pulpería",
    vsBot: "Contra la compu",
    local: "2 jugadores",
    localNote: "En el mismo teclado",
    online: "En línea",
    onlineNote: "Con código de sala",
    levels: { easy: "Fácil", normal: "Normal", hard: "Difícil" } satisfies Record<Level, string>,
    firstTo: (n: number) => `Gana el primero en llegar a ${n}`,
    controlsMouse: "Mouse: mover tus barras. Clic: patear, mantén para más fuerza",
    controlsRed: "Rojo: W / S para mover, D para patear",
    controlsBlue: "Azul: flechas arriba / abajo para mover, flecha izquierda para patear",
    controlsCamera: "Clic derecho y arrastrar: mover la cámara. Rueda: acercar. Espacio: sacar de nuevo",
    goal: "¡GOOOL!",
    matchPoint: "Punto de partido",
    won: (team: string) => `¡Ganó ${team}!`,
    rematch: "Revancha",
    menu: "Menú",
    resetView: "Cámara",
    lang: "English",
    sound: { on: "Sonido: sí", off: "Sonido: no" },
    radio: "En la radio",
    powers: { fuego: "Fuego", turbo: "Turbo", oxido: "Óxido", hielo: "Hielo" } satisfies Record<Power, string>,
    powersNote: "Pasa la pelota sobre las corcholatas para agarrar poderes",
  },
  en: {
    title: "La Barra",
    tagline: "Corner-shop table football",
    vsBot: "Against the computer",
    local: "2 players",
    localNote: "On one keyboard",
    online: "Online",
    onlineNote: "With a room code",
    levels: { easy: "Easy", normal: "Normal", hard: "Hard" } satisfies Record<Level, string>,
    firstTo: (n: number) => `First to ${n} wins`,
    controlsMouse: "Mouse: move your rods. Click: kick, hold for power",
    controlsRed: "Red: W / S to move, D to kick",
    controlsBlue: "Blue: arrow up / down to move, arrow left to kick",
    controlsCamera: "Right-click and drag: move the camera. Wheel: zoom. Space: serve again",
    goal: "GOOOAL!",
    matchPoint: "Match point",
    won: (team: string) => `${team} wins!`,
    rematch: "Rematch",
    menu: "Menu",
    resetView: "Camera",
    lang: "Español",
    sound: { on: "Sound: on", off: "Sound: off" },
    radio: "On the radio",
    powers: { fuego: "Fire", turbo: "Turbo", oxido: "Rust", hielo: "Ice" } satisfies Record<Power, string>,
    powersNote: "Roll the ball over the bottle caps to grab powers",
  },
} as const satisfies Record<Lang, unknown>;

export type Strings = (typeof strings)[Lang];
