import type { Level } from "@/game/bot";
import type { Power } from "@/game/powerups";

export type Lang = "es" | "en";

export const strings = {
  es: {
    title: "La Barra",
    tagline: "Futbolito de pulpería",
    vsBot: "Contra la compu",
    local: "2 jugadores",
    localNote: "En el mismo teclado",
    online: "En línea",
    onlineNote: "Con código de sala",
    levels: { easy: "Fácil", normal: "Normal", hard: "Difícil" } satisfies Record<Level, string>,
    firstTo: (n: number) => `Gana el primero en llegar a ${n}`,
    controlsMouse: "Mouse: mover tus barras. Clic: patear, mantén para más fuerza. Clic derecho: pase",
    controlsRed: "Rojo: W / S para mover, D para patear, A para pasar",
    controlsBlue: "Azul: flechas arriba / abajo para mover, flecha izquierda para patear, flecha derecha para pasar",
    controlsCamera: "Clic derecho y arrastrar: mover la cámara. Rueda: acercar. Espacio: sacar de nuevo",
    goal: "¡GOOOL!",
    matchPoint: "Punto de partido",
    won: (team: string) => `¡Ganó ${team}!`,
    rematch: "Revancha",
    menu: "Menú",
    resetView: "Cámara",
    lang: "English",
    sound: { on: "Sonido: sí", off: "Sonido: no" },
    radio: "En la radio",
    powers: { fuego: "Fuego", turbo: "Turbo", oxido: "Óxido", hielo: "Hielo" } satisfies Record<Power, string>,
    powersNote: "Pasa la pelota sobre las chapas para agarrar poderes",
    today: "Hoy se juega",
    signLine: "Atlético La Esquina contra Real Pulpería",
    options: "Opciones",
    howTo: "Cómo se juega",
    pause: {
      title: "Pausa",
      open: "Pausa",
      resume: "Seguir jugando",
      restart: "Empezar de nuevo",
      quit: "Salir al menú",
      online: "En línea la partida no se detiene.",
    },
    hud: { camera: "Volver a la vista de juego", soundOn: "Quitar el sonido", soundOff: "Poner el sonido" },
    settings: {
      title: "Opciones",
      close: "Cerrar",
      tabs: { look: "Sonido e imagen", access: "Accesibilidad", controls: "Controles" },
      yes: "Sí",
      no: "No",
      sound: ["Sonido", "Golpes, paredes, silbato y la barra de la pulpería."],
      volume: ["Volumen", ""],
      quality: ["Calidad de imagen", "Baja quita las sombras: va más fluido en computadoras lentas."],
      high: "Alta",
      low: "Baja",
      language: ["Idioma", ""],
      reduceMotion: ["Reducir movimiento", "Sin letras que rebotan, sin confeti y sin sacudidas."],
      shake: ["Sacudida de cámara", "La mesa tiembla con los goles y los cañonazos."],
      textSize: ["Tamaño del texto", ""],
      sizes: { 1: "Normal", 1.15: "Grande", 1.3: "Muy grande" },
      contrast: ["Alto contraste", "Fondo sólido detrás de todo texto sobre la mesa."],
      subtitles: ["Subtítulos de Don Chepe", "Lo que dice el narrador de la radio, en pantalla."],
      hints: ["Recordatorio de controles", "Las teclas y botones, abajo durante el partido."],
      teamsNote: "Los equipos también se distinguen por la forma del escudo: redondo el rojo, de punta el azul.",
    },
    guide: {
      mouse: "Mouse",
      touch: "Pantalla táctil",
      red: "Rojo en el teclado",
      blue: "Azul en el teclado",
      move: "Mover",
      kick: "Patear",
      pass: "Pase",
      camera: "Cámara",
      point: "Apunta a lo ancho de la mesa",
      click: "Clic (mantén para más fuerza)",
      rightTap: "Clic derecho rápido",
      rightDrag: "Clic derecho y arrastrar, rueda para acercar",
      slide: "Desliza un dedo",
      tap: "Toca (mantén para más fuerza)",
      twoTap: "Toque rápido con dos dedos",
      twoDrag: "Dos dedos y arrastrar",
      space: "Espacio",
      serve: "pelota nueva",
      rules: [
        "La barra más cerca de la pelota es la que patea: tú solo mueves y disparas.",
        "El pase manda la pelota a tu barra de adelante, al compañero más libre. Esa barra levanta los pies, la deja pasar y la atrapa.",
        "Las chapas que caen dan un poder por unos segundos al último que tocó la pelota.",
        "Gana el primero en llegar a 5. Espacio saca una pelota nueva.",
      ],
    },
    net: {
      title: "En línea",
      host: "Crear sala",
      hostNote: "Juegas con rojo",
      join: "Unirse",
      joinNote: "Juegas con azul",
      yourCode: "Código de tu sala",
      waiting: "Esperando a tu rival…",
      shareLink: "Copiar link para invitar",
      copied: "Link copiado",
      codeLabel: "Código de la sala",
      enter: "Entrar",
      connecting: "Conectando…",
      back: "Volver",
      notFound: "No encontré esa sala. Revisa el código.",
      unreachable: "La sala existe, pero no se pudo conectar con tu rival. Puede ser la red de alguno de los dos; intenten otra vez.",
      network: "No se pudo conectar. Revisa tu internet e intenta otra vez.",
      left: "Tu rival se desconectó.",
      waitingRematch: "Esperando a que el anfitrión pida revancha…",
      guestControls: "Mouse: mover tus barras (azules). Clic: patear. Clic derecho: pase",
    },
  },
  en: {
    title: "La Barra",
    tagline: "Corner-shop table football",
    vsBot: "Against the computer",
    local: "2 players",
    localNote: "On one keyboard",
    online: "Online",
    onlineNote: "With a room code",
    levels: { easy: "Easy", normal: "Normal", hard: "Hard" } satisfies Record<Level, string>,
    firstTo: (n: number) => `First to ${n} wins`,
    controlsMouse: "Mouse: move your rods. Click: kick, hold for power. Right-click: pass",
    controlsRed: "Red: W / S to move, D to kick, A to pass",
    controlsBlue: "Blue: arrow up / down to move, arrow left to kick, arrow right to pass",
    controlsCamera: "Right-click and drag: move the camera. Wheel: zoom. Space: serve again",
    goal: "GOOOAL!",
    matchPoint: "Match point",
    won: (team: string) => `${team} wins!`,
    rematch: "Rematch",
    menu: "Menu",
    resetView: "Camera",
    lang: "Español",
    sound: { on: "Sound: on", off: "Sound: off" },
    radio: "On the radio",
    powers: { fuego: "Fire", turbo: "Turbo", oxido: "Rust", hielo: "Ice" } satisfies Record<Power, string>,
    powersNote: "Roll the ball over the bottle caps to grab powers",
    today: "Playing today",
    signLine: "Atlético La Esquina against Real Pulpería",
    options: "Options",
    howTo: "How to play",
    pause: {
      title: "Paused",
      open: "Pause",
      resume: "Keep playing",
      restart: "Start over",
      quit: "Back to the menu",
      online: "Online, the match doesn't stop.",
    },
    hud: { camera: "Back to the playing view", soundOn: "Mute", soundOff: "Unmute" },
    settings: {
      title: "Options",
      close: "Close",
      tabs: { look: "Sound and picture", access: "Accessibility", controls: "Controls" },
      yes: "On",
      no: "Off",
      sound: ["Sound", "Kicks, walls, the whistle and the shop cheering."],
      volume: ["Volume", ""],
      quality: ["Picture quality", "Low drops the shadows: smoother on slower computers."],
      high: "High",
      low: "Low",
      language: ["Language", ""],
      reduceMotion: ["Reduce motion", "No bouncing lettering, no confetti and no shaking."],
      shake: ["Camera shake", "The table shakes on goals and big shots."],
      textSize: ["Text size", ""],
      sizes: { 1: "Normal", 1.15: "Large", 1.3: "Extra large" },
      contrast: ["High contrast", "A solid backing behind all text over the table."],
      subtitles: ["Don Chepe's subtitles", "What the radio commentator says, on screen."],
      hints: ["Controls reminder", "The keys and buttons, at the bottom during a match."],
      teamsNote: "The teams also differ in crest shape: round for red, pointed for blue.",
    },
    guide: {
      mouse: "Mouse",
      touch: "Touch screen",
      red: "Red on the keyboard",
      blue: "Blue on the keyboard",
      move: "Move",
      kick: "Kick",
      pass: "Pass",
      camera: "Camera",
      point: "Point across the table",
      click: "Click (hold for power)",
      rightTap: "Quick right-click",
      rightDrag: "Right-drag, wheel to zoom",
      slide: "Slide a finger",
      tap: "Tap (hold for power)",
      twoTap: "Quick two-finger tap",
      twoDrag: "Two-finger drag",
      space: "Space",
      serve: "new ball",
      rules: [
        "The rod nearest the ball is the one that kicks: you only move and shoot.",
        "A pass sends the ball to your next rod up, to the freest teammate. That rod lifts its feet, lets it under and traps it.",
        "Falling bottle caps give a power for a few seconds to whoever touched the ball last.",
        "First to 5 wins. Space serves a new ball.",
      ],
    },
    net: {
      title: "Online",
      host: "Create a room",
      hostNote: "You play red",
      join: "Join",
      joinNote: "You play blue",
      yourCode: "Your room code",
      waiting: "Waiting for your opponent…",
      shareLink: "Copy invite link",
      copied: "Link copied",
      codeLabel: "Room code",
      enter: "Join",
      connecting: "Connecting…",
      back: "Back",
      notFound: "Couldn't find that room. Check the code.",
      unreachable: "The room is there, but your opponent couldn't be reached. One of your networks may be blocking it; try again.",
      network: "Couldn't connect. Check your internet and try again.",
      left: "Your opponent disconnected.",
      waitingRematch: "Waiting for the host to call a rematch…",
      guestControls: "Mouse: move your (blue) rods. Click: kick. Right-click: pass",
    },
  },
} as const satisfies Record<Lang, unknown>;

export type Strings = (typeof strings)[Lang];
